title: Enablis Policies
description: A home for Enablis policies and associated documentation
theme: minima # This is a simple default theme
baseurl: "/policies" # This should match the repository name
url: "https://enablis-co.github.io" # Your GitHub domain

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-search

# Add these lines to your existing config
include:
  - Policies
  - Procedures
  - Guides

# Optional: Set default layouts for files in these directories
defaults:
  - scope:
      path: "Policies"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "Procedures"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "Guides"
      type: "pages"
    values:
      layout: "page" 